<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="8542" started-at="2018-07-13T07:41:51Z" finished-at="2018-07-13T07:42:00Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="8542" started-at="2018-07-13T07:41:51Z" finished-at="2018-07-13T07:42:00Z">
      <class name="testFramework.ArcherTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="beforeSuite" is-config="true" duration-ms="106" started-at="2018-07-13T13:11:51Z" finished-at="2018-07-13T13:11:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="beforeClass" is-config="true" duration-ms="3" started-at="2018-07-13T13:11:51Z" finished-at="2018-07-13T13:11:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="setup()[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="setup" is-config="true" duration-ms="0" started-at="2018-07-13T13:11:51Z" finished-at="2018-07-13T13:11:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="beforeMethod(java.lang.reflect.Method)[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="beforeMethod" is-config="true" duration-ms="3759" started-at="2018-07-13T13:11:51Z" finished-at="2018-07-13T13:11:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testFramework.ArcherTest.createSolution() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="beforeMethod" is-config="true" duration-ms="2553" started-at="2018-07-13T13:11:55Z" finished-at="2018-07-13T13:11:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="createSolution()[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="createSolution" duration-ms="99" started-at="2018-07-13T13:11:57Z" description="This test cases is for Login in to Archer Instance and creating the solution" finished-at="2018-07-13T13:11:58Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.testframework.common.DriverMethods.implicitlyWait(DriverMethods.java:517)
	at com.testframework.common.DriverMethods.clickPerformWhenReady(DriverMethods.java:368)
	at com.testframework.pageclasses.HomePage.createSolution(HomePage.java:20)
	at testFramework.ArcherTest.createSolution(ArcherTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSolution -->
        <test-method status="PASS" signature="afterMethod(java.lang.reflect.Method, org.testng.ITestResult)[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="afterMethod" is-config="true" duration-ms="1839" started-at="2018-07-13T13:11:58Z" finished-at="2018-07-13T13:11:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testFramework.ArcherTest.createSolution() throws java.lang.InterruptedException]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[[TestResult name=createSolution status=FAILURE method=ArcherTest.createSolution()[pri:0, instance:testFramework.ArcherTest@14a4e18] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:testFramework.ArcherTest@14a4e18]" name="afterMethod" is-config="true" duration-ms="256" started-at="2018-07-13T13:11:59Z" finished-at="2018-07-13T13:12:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=createSolution status=FAILURE method=ArcherTest.createSolution()[pri:0, instance:testFramework.ArcherTest@14a4e18] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- testFramework.ArcherTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
